### ISSUE TITLE
ranking system

### ISSUE THREAD

**Issue by Acg1000** [UHCBot/Referee#20]
Could we create a point system for the UHCers? Where when you win we can use commands to tell that bot how many points you have received then once you get to a certain amount of points it assigns you a role?

**Comment by MrLotU** [comment]
I'll be setting this up next. I'll start on it once I have vacation (3-4 weeks)

**Comment by MrLotU** [comment]
All done and implemented in https://github.com/UHCBot/Referee/commit/4718f9b28ac29e0cc1ddc2ed5d64534f978c03ae
