### ISSUE TITLE
Embedded time announcements

### ISSUE THREAD

**Issue by Acg1000** [UHCBot/Referee#33]
Have the bot post an embed with time zone conversions for a certain event when a command is run in the bot testing / mod chat channel

**Comment by MrLotU** [comment]
I think I get where you're going, but could you give me an example?

**Comment by Acg1000** [comment]
@MrLotU let's say we want to announce a UHC and show the times it's going to occur. We can run a command that posts the times for the morning and evening events in a nicly formatted embed.

**Comment by MrLotU** [comment]
Could you give me a 
```diff
+user
-bot
```
type of example?

**Comment by Acg1000** [comment]
User - `!announce <time> <channel>`
Bot - `<times in the major time conversions>`

I thought this might be a way to do it. You will probably have a better way though.

**Comment by MrLotU** [comment]
Implemented in https://github.com/UHCBot/Referee/commit/01eead8447dc87e0857bd996a6207332442624e2
