### ISSUE TITLE
User Joining Feedback

### ISSUE THREAD

**Issue by MonkeyDKS** [UHCBot/Referee#34]
I'd love it if we could give the user as much feedback as possible.  Maybe when they first join the Discord, before they even pick the game category they want to be in, we require them to fill out some metadata... maybe not.

But the for the actual issue, we should provide a confirmation feedback when someone joins so they know they joined the match they wanted to.

So say I clicked the !joinRL reaction... The referee should tell me, MonkeyDKS joined rocket league match on Nov 11 at [9:00]pm [EST] with the Steam Account Name: MonkeyDKS

**Comment by MrLotU** [comment]
Can be implemented on a per game basis because of #29, #27 and magic:tm:
