### ISSUE TITLE
Add to MetaData

### ISSUE THREAD

**Issue by MonkeyDKS** [UHCBot/Referee#35]
- [ ] Twitter

- [ ] YouTube

- [ ] Mixer/Twitch

- [ ] A way for mods to add a field later?  Maybe admin only so as not to add random useless fields that are hard to purge later... but more than just one person should be able to add them I think... just in case you're not around.

**Comment by MrLotU** [comment]
@MonkeyDKS Sounds good! (don't mind the late reply) I'll probs get them in the db!

**Comment by MrLotU** [comment]
Closing this for now. The bot doesn't need this data and people can just look at discord profiles. Might re-open in the future when the bot has a use for this.
